# Generated by Django 3.0.8 on 2020-07-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmanage', '0002_auto_20200725_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stockmanage.Category'),
            preserve_default=False,
        ),
    ]
